apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: nest
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008  # Must be in range 30000-32767
  type: NodePort
